# -*- coding: utf-8 -*-
"""00_jupyterlab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1pjdfmS7cv6HpnvWJ-UaBkx3atNYW20

<center><a href="https://www.nvidia.com/en-us/training/"><img src="https://dli-lms.s3.amazonaws.com/assets/general/DLI_Header_White.png" width="400" height="186" /></a></center>

<br>

# <font color="#76b900">**Notebook 0:** JupyterLab</font>

<br>

We use [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) to manage our environment for this hands-on lab. The [JupyterLab Interface](https://jupyterlab.readthedocs.io/en/stable/user/interface.html) is a dashboard that provides access to interactive iPython notebooks, as well as the folder structure of our environment and a terminal window into the Ubuntu operating system. The view includes a **menu bar** at the top, a **file browser** in the **left sidebar**, and a **main work area** initially open to the "Launcher" page.

<br>
<!-- <img src="https://drive.google.com/uc?export=view&id=1FJHrWRBc5s5zcZFb19sC-U64qNkf67Jt"> -->
> <img src="https://dli-lms.s3.amazonaws.com/assets/s-fx-15-v1/imgs/jl_launcher.png" width=1000px/>
<br>

### **Some Notes:**

- You can navigate the file browser just like any other file explorer. A double click on any of the items will open a new tab with its content.
- The main work area includes tabbed views of open files that can be closed, moved, and edited as needed.
- The notebooks, including this one, contain a series of content and code **cells**. To execute code in a code cell, press `Shift+Enter` or the "Run" button in the menu bar above while highlighting a cell. Sometimes, a content cell will get switched to editing mode, in which case you can press `Shift+Enter` to change it back to a readable form.

**Try executing the simple print statement in the cell below.**
"""

# Highlight this cell and click [Shift+Enter] to execute
print('This is just a simple print statement')

"""----

<br>

## **Special Syntax**

This course uses some intermediate Python syntax, including some implicit assumptions that need clarification. We'll be sure to clarify most of this content as the course progresses, but the following components may be helpful to know ahead of time:

**Inputs, Passwords, and Secrets**:
- `input` and `getpass` may be used, which will cause input fields to pop up under notebook cells. ***If an input request is open and you try to run another cell, your notebook will stall at the input cell or a popup error will tell you to finish your input***. Use the square ( $\square$ ) button or enter the prompt to continue if this happens. Here is an example:
"""

from getpass import getpass
from pydantic import SecretStr

first_name = input("Enter your name: ")
print(f"Hello {first_name}\n")   ## F-strings. Commonly used to fill in variables

secret = SecretStr(getpass("Please tell me a secret: "))
print("Your secret is:", secret)  ## Another way to print multiple values. sep=" " is default
# print("Your secret value is:", secret.get_secret_value())

"""**Multi-Line Grouping:**
- In Python, a language sensitive to tabbing and newlines, some components can be grouped using parentheses. When you distribute code over multiple lines, newlines will be interpreted as spaces, as shown below:
"""

################################################################################
## Implicit string concatenation. Interpretted as `print( "Hello" "World" )`
print(
    "Hello" "World"
)

################################################################################
## Implicit string concatenation. Interpretted as `print( "5" " " "8" )`
print((
    "5" " "
    "8"
))

print(
    5 +
    6
)

################################################################################
## The below line is considered bad syntax, and the cell will fail to evaluate
# 5 +
# 6

################################################################################
## The following forcefully tries to run contents of the following line:
try:
    eval("5 + \n6")
except Exception as e:
    print(e)

################################################################################
## Useful example, where lines can be commented out to remove functionality:
(
    f"Hello {first_name}"
        .upper()
        + '!!'
        # '!!!'    ## Uncomment to add even more. Useful for organizing
        ' It\'s so nice to meet you!'

)

"""-----

<br>

## **Wrap-Up**

Now that we have the basics down, we're ready to get started with the course! Please continue on to the next video and, subsequently, `01_environment.ipynb`, where you'll learn about the environmental setup of the course!

### <font color="#76b900">**Good Luck!**</font>

<br>

---

<center><a href="https://www.nvidia.com/dli"> <img src="https://dli-lms.s3.amazonaws.com/assets/general/DLI_Header_White.png" alt="Header" style="width: 400px;"/> </a></center>
"""